[server]
ip = "0.0.0.0"
port = 8080

[[stocks]]
name = "RTX3090"
sites = [
{provider = "kakaku", url = "https://kakaku.com/pc/videocard/itemlist.aspx?pdf_Spec103=481"},
]
threshold = 230_000

[[stocks]]
name = "RTX3080"
sites = [
{provider = "kakaku", url = "https://kakaku.com/pc/videocard/itemlist.aspx?pdf_Spec103=480"},
]
threshold = 130_000

[[stocks]]
name = "RTX3070"
sites = [
{provider = "kakaku", url = "https://kakaku.com/pc/videocard/itemlist.aspx?pdf_Spec103=479"},
]
threshold = 100_000

[[stocks]]
name = "RTX3060Ti"
sites = [
{provider = "kakaku", url = "https://kakaku.com/pc/videocard/itemlist.aspx?pdf_Spec103=482"},
]
threshold = 70_000

[[stocks]]
name = "RTX3060"
sites = [
{provider = "kakaku", url = "https://kakaku.com/pc/videocard/itemlist.aspx?pdf_Spec103=484"},
]
threshold = 60_000
